name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Run Tests with Maven
        run: mvn clean test
      - name: Generate Test Coverage Report
        run: mvn jacoco:report
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          min-coverage-overall: 100
          min-coverage-changed-files: 100
          distribution: 'ubuntu'
