name: Measure coverage

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Tests with Maven
        run: mvn clean test
      - name: Generate Test Coverage Report
        run: mvn jacoco:report
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 100
          min-coverage-changed-files: 100
          debug-mode: true
          title: ':coffee: Coverage report'
          pass-emoji: ':nail_care:'
          fail-emoji: ':skull:'
      - name: Fail PR if overall coverage is less than 100%
        if: ${{ steps.jacoco.outputs.coverage-overall < 100.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 100%!')
